version: '3'
services:
  react-ui:
    build:
      context: .
      args:
        - REACT_APP_NOT_SECRET_CODE=$NOT_SECRET_CODE
        - REACT_APP_JAVA_HOME=$JAVA_HOME
    ports:
      - "3001:3000"
    container_name: hello
    stdin_open: true