FROM node:latest
WORKDIR /app
ARG REACT_APP_NOT_SECRET_CODE
ENV REACT_APP_NOT_SECRET_CODE=$REACT_APP_NOT_SECRET_CODE
ARG REACT_APP_JAVA_HOME
ENV REACT_APP_JAVA_HOME=$REACT_APP_JAVA_HOME
COPY package.json ./
RUN npm install
COPY . .
CMD ["npm", "start"]